services:
  postgres:
    container_name: postgres_container
    image: postgres:16.3-alpine
    environment:
      - POSTGRES_USER=postgres 
      - POSTGRES_PASSWORD=pass
      - PGDATA=/data/postgres
    volumes:
       - postgres:/data/postgres
    ports:
      - "5432:5432"
  
volumes:
    postgres: