services:
  postgres:
    container_name: dev_postgres
    image: postgres:16.3-alpine
    environment:
      POSTGRES_PASSWORD: pass
    volumes:
       - postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  
volumes:
    postgres: